// ── IDIOM CARDS ───────────────────────────────
// Collectibles from Epic and Legendary chests (alongside cosmetics): real
// idioms of the language you learn, each with its word-for-word meaning,
// what it really means and an example. Shown in 🎨 Collection → 📜 Idioms.
// Fields: id, rar (epic | legendary), icon, p (the idiom), lit (word for
// word), mean (what it means), ex (example), exT (its translation).
// Ids are stable — owned cards are stored by id in S.quests.idioms.

const IDIOMS_DE = [
  // legendary
  { id: "de_schwein_pfeift", rar: "legendary", icon: "🐷", p: "Ich glaub, mein Schwein pfeift!", lit: "I think my pig is whistling!", mean: "I can't believe it!", ex: "Du hast die Prüfung bestanden? Ich glaub, mein Schwein pfeift!", exT: "You passed the exam? I can't believe it!" },
  { id: "de_baer_steppt", rar: "legendary", icon: "🐻", p: "Da steppt der Bär", lit: "The bear tap-dances there", mean: "It's a great party, lots going on", ex: "Komm heute Abend mit, da steppt der Bär!", exT: "Come along tonight, it's going to be a blast!" },
  { id: "de_wurst_zwei", rar: "legendary", icon: "🌭", p: "Alles hat ein Ende, nur die Wurst hat zwei", lit: "Everything has an end, only the sausage has two", mean: "All good things come to an end", ex: "Der Urlaub ist vorbei – alles hat ein Ende, nur die Wurst hat zwei.", exT: "The holiday is over — all good things come to an end." },
  { id: "de_affe_tot", rar: "legendary", icon: "🐒", p: "Klappe zu, Affe tot", lit: "Flap shut, monkey dead", mean: "And that's that — it's settled", ex: "Wir nehmen das blaue Auto. Klappe zu, Affe tot.", exT: "We're taking the blue car. End of story." },
  { id: "de_hummeln", rar: "legendary", icon: "🐝", p: "Hummeln im Hintern haben", lit: "To have bumblebees in your bottom", mean: "To be restless, unable to sit still", ex: "Das Kind hat heute Hummeln im Hintern.", exT: "The child can't sit still today." },
  { id: "de_laus_leber", rar: "legendary", icon: "🐜", p: "Ist dir eine Laus über die Leber gelaufen?", lit: "Did a louse run over your liver?", mean: "Why are you in such a bad mood?", ex: "Du bist so schlecht gelaunt – ist dir eine Laus über die Leber gelaufen?", exT: "You're so grumpy — what's eating you?" },
  { id: "de_fuchs_hase", rar: "legendary", icon: "🦊", p: "Wo sich Fuchs und Hase gute Nacht sagen", lit: "Where fox and hare say good night", mean: "In the middle of nowhere", ex: "Meine Oma wohnt, wo sich Fuchs und Hase gute Nacht sagen.", exT: "My grandma lives in the middle of nowhere." },
  { id: "de_bahnhof", rar: "legendary", icon: "🚉", p: "Ich verstehe nur Bahnhof", lit: "I only understand 'train station'", mean: "It's all Greek to me", ex: "Er erklärt mir Physik, aber ich verstehe nur Bahnhof.", exT: "He explains physics to me, but it's all Greek to me." },
  { id: "de_tomaten", rar: "legendary", icon: "🍅", p: "Tomaten auf den Augen haben", lit: "To have tomatoes on your eyes", mean: "To miss something obvious", ex: "Die Brille liegt vor dir! Hast du Tomaten auf den Augen?", exT: "The glasses are right in front of you! Are you blind?" },
  { id: "de_baer_aufbinden", rar: "legendary", icon: "🧸", p: "Jemandem einen Bären aufbinden", lit: "To tie a bear onto someone", mean: "To pull someone's leg", ex: "Du willst mir einen Bären aufbinden!", exT: "You're pulling my leg!" },
  { id: "de_gott_frankreich", rar: "epic", icon: "🥂", p: "Leben wie Gott in Frankreich", lit: "To live like God in France", mean: "To live in luxury", ex: "Im Hotel haben wir gelebt wie Gott in Frankreich.", exT: "At the hotel we lived like kings." },
  { id: "de_wurst", rar: "epic", icon: "🥨", p: "Das ist mir Wurst", lit: "That's sausage to me", mean: "I don't care", ex: "Pizza oder Pasta? Das ist mir Wurst.", exT: "Pizza or pasta? I don't mind." },
  // epic
  { id: "de_schwein_haben", rar: "epic", icon: "🐖", p: "Schwein haben", lit: "To have pig", mean: "To be lucky", ex: "Der Bus war noch da – Schwein gehabt!", exT: "The bus was still there — lucky!" },
  { id: "de_daumen", rar: "epic", icon: "👍", p: "Jemandem die Daumen drücken", lit: "To press your thumbs for someone", mean: "To keep your fingers crossed", ex: "Ich drücke dir morgen die Daumen!", exT: "I'll keep my fingers crossed for you tomorrow!" },
  { id: "de_katze_sack", rar: "epic", icon: "🐈", p: "Die Katze im Sack kaufen", lit: "To buy the cat in the sack", mean: "To buy something without seeing it first", ex: "Ich will das Auto erst testen – ich kaufe keine Katze im Sack.", exT: "I want to test the car first — I won't buy blind." },
  { id: "de_nagel", rar: "epic", icon: "🔨", p: "Den Nagel auf den Kopf treffen", lit: "To hit the nail on the head", mean: "To be exactly right", ex: "Mit deiner Antwort hast du den Nagel auf den Kopf getroffen.", exT: "You hit the nail on the head with your answer." },
  { id: "de_bier", rar: "epic", icon: "🍺", p: "Das ist nicht mein Bier", lit: "That's not my beer", mean: "That's not my business", ex: "Wie er sein Geld ausgibt, ist nicht mein Bier.", exT: "How he spends his money is none of my business." },
  { id: "de_brei", rar: "epic", icon: "🥣", p: "Um den heißen Brei herumreden", lit: "To talk around the hot porridge", mean: "To beat around the bush", ex: "Red nicht um den heißen Brei herum – was ist los?", exT: "Stop beating around the bush — what's wrong?" },
  { id: "de_kater", rar: "epic", icon: "😿", p: "Einen Kater haben", lit: "To have a tomcat", mean: "To have a hangover", ex: "Nach der Party hatte ich einen schlimmen Kater.", exT: "After the party I had a terrible hangover." },
  { id: "de_nase_voll", rar: "epic", icon: "👃", p: "Die Nase voll haben", lit: "To have your nose full", mean: "To be fed up", ex: "Ich habe die Nase voll vom Regen.", exT: "I'm fed up with the rain." },
  { id: "de_keks", rar: "epic", icon: "🍪", p: "Jemandem auf den Keks gehen", lit: "To walk on someone's biscuit", mean: "To get on someone's nerves", ex: "Dein Handy geht mir echt auf den Keks.", exT: "Your phone is really getting on my nerves." },
  { id: "de_fettnaepfchen", rar: "epic", icon: "🫕", p: "Ins Fettnäpfchen treten", lit: "To step into the little pot of fat", mean: "To put your foot in it", ex: "Mit der Frage nach seiner Ex bin ich voll ins Fettnäpfchen getreten.", exT: "Asking about his ex, I really put my foot in it." },
  { id: "de_affe", rar: "epic", icon: "🙈", p: "Sich zum Affen machen", lit: "To make yourself into a monkey", mean: "To make a fool of yourself", ex: "Beim Karaoke habe ich mich zum Affen gemacht.", exT: "I made a fool of myself at karaoke." },
  { id: "de_hund_begraben", rar: "epic", icon: "🐕", p: "Da liegt der Hund begraben", lit: "That's where the dog is buried", mean: "That's the heart of the problem", ex: "Wir haben kein Geld – da liegt der Hund begraben.", exT: "We have no money — that's the real problem." },
  { id: "de_holzweg", rar: "epic", icon: "🪵", p: "Auf dem Holzweg sein", lit: "To be on the wood path", mean: "To be on the wrong track", ex: "Wenn du das glaubst, bist du auf dem Holzweg.", exT: "If you believe that, you're barking up the wrong tree." },
  { id: "de_hals_bein", rar: "epic", icon: "🦵", p: "Hals- und Beinbruch!", lit: "Neck and leg break!", mean: "Good luck! (break a leg)", ex: "Morgen ist dein Konzert? Hals- und Beinbruch!", exT: "Your concert is tomorrow? Break a leg!" },
  { id: "de_huehnchen", rar: "epic", icon: "🐔", p: "Mit jemandem ein Hühnchen rupfen", lit: "To pluck a little chicken with someone", mean: "To have a bone to pick with someone", ex: "Mit dir habe ich noch ein Hühnchen zu rupfen!", exT: "I've got a bone to pick with you!" },
  { id: "de_kohldampf", rar: "epic", icon: "🥬", p: "Kohldampf haben", lit: "To have cabbage steam", mean: "To be starving", ex: "Nach der Wanderung hatten alle Kohldampf.", exT: "After the hike everyone was starving." },
  { id: "de_gelbe_ei", rar: "epic", icon: "🥚", p: "Nicht das Gelbe vom Ei", lit: "Not the yellow of the egg", mean: "Not ideal, not great", ex: "Das Hotel war nicht gerade das Gelbe vom Ei.", exT: "The hotel wasn't exactly great." },
  { id: "de_extrawurst", rar: "epic", icon: "🌭", p: "Eine Extrawurst bekommen", lit: "To get an extra sausage", mean: "To get special treatment", ex: "Warum bekommt er immer eine Extrawurst?", exT: "Why does he always get special treatment?" },
  { id: "de_sau", rar: "epic", icon: "🐗", p: "Unter aller Sau", lit: "Below every sow", mean: "Absolutely terrible", ex: "Das Essen war unter aller Sau.", exT: "The food was absolutely awful." },
  { id: "de_fliegen", rar: "epic", icon: "🪰", p: "Zwei Fliegen mit einer Klappe schlagen", lit: "To swat two flies with one swatter", mean: "To kill two birds with one stone", ex: "Ich jogge zur Arbeit – so schlage ich zwei Fliegen mit einer Klappe.", exT: "I jog to work — two birds with one stone." },
  { id: "de_wein", rar: "epic", icon: "🍷", p: "Jemandem reinen Wein einschenken", lit: "To pour someone pure wine", mean: "To tell someone the plain truth", ex: "Ich muss dir jetzt reinen Wein einschenken.", exT: "I have to be honest with you now." },
  { id: "de_teufel", rar: "epic", icon: "😈", p: "Den Teufel an die Wand malen", lit: "To paint the devil on the wall", mean: "To imagine the worst", ex: "Mal nicht gleich den Teufel an die Wand!", exT: "Don't assume the worst right away!" },
  { id: "de_grossem_fuss", rar: "epic", icon: "🦶", p: "Auf großem Fuß leben", lit: "To live on a big foot", mean: "To live extravagantly", ex: "Seit dem Lottogewinn lebt er auf großem Fuß.", exT: "Since winning the lottery he lives the high life." },
  { id: "de_lange_bank", rar: "epic", icon: "🪑", p: "Etwas auf die lange Bank schieben", lit: "To push something onto the long bench", mean: "To put something off", ex: "Schieb die Steuererklärung nicht auf die lange Bank!", exT: "Don't put off your tax return!" },
  { id: "de_katzensprung", rar: "epic", icon: "🐾", p: "Ein Katzensprung", lit: "A cat's jump", mean: "A stone's throw away", ex: "Der Bahnhof ist nur einen Katzensprung entfernt.", exT: "The station is just a stone's throw away." },
  { id: "de_sturmfrei", rar: "epic", icon: "🏠", p: "Sturmfreie Bude haben", lit: "To have a storm-free den", mean: "To have the place to yourself", ex: "Meine Eltern sind weg – ich habe sturmfreie Bude!", exT: "My parents are away — I've got the place to myself!" },
  { id: "de_senf", rar: "epic", icon: "🟡", p: "Seinen Senf dazugeben", lit: "To add your mustard", mean: "To give your two cents", ex: "Muss er immer seinen Senf dazugeben?", exT: "Does he always have to put his two cents in?" },
  { id: "de_blau", rar: "epic", icon: "🔵", p: "Blau sein", lit: "To be blue", mean: "To be drunk", ex: "Nach drei Bier war er schon blau.", exT: "After three beers he was already drunk." },
  { id: "de_fix_fertig", rar: "epic", icon: "😵", p: "Fix und fertig sein", lit: "To be fixed and finished", mean: "To be completely exhausted", ex: "Nach dem Umzug war ich fix und fertig.", exT: "After the move I was completely worn out." },
  { id: "de_kirche", rar: "epic", icon: "⛪", p: "Die Kirche im Dorf lassen", lit: "To leave the church in the village", mean: "Not to get carried away", ex: "Lass mal die Kirche im Dorf – es war nur ein kleiner Fehler.", exT: "Let's not overreact — it was just a small mistake." },
  { id: "de_brett", rar: "epic", icon: "🧱", p: "Ein Brett vor dem Kopf haben", lit: "To have a board in front of your head", mean: "To be slow on the uptake", ex: "Heute habe ich echt ein Brett vor dem Kopf.", exT: "My brain just isn't working today." },
  { id: "de_muecke", rar: "epic", icon: "🐘", p: "Aus einer Mücke einen Elefanten machen", lit: "To make an elephant out of a mosquito", mean: "To make a mountain out of a molehill", ex: "Mach doch aus einer Mücke keinen Elefanten!", exT: "Don't make a mountain out of a molehill!" },
  { id: "de_um_die_wurst", rar: "epic", icon: "🏁", p: "Jetzt geht's um die Wurst", lit: "Now it's about the sausage", mean: "Now it really counts", ex: "Letztes Spiel der Saison – jetzt geht's um die Wurst!", exT: "Last game of the season — this is it!" },
  { id: "de_tote_hose", rar: "epic", icon: "👖", p: "Tote Hose", lit: "Dead trousers", mean: "Nothing going on, boring", ex: "Am Sonntag ist in der Stadt tote Hose.", exT: "On Sundays there's nothing going on in town." },
  { id: "de_spanisch", rar: "epic", icon: "💃", p: "Das kommt mir spanisch vor", lit: "That seems Spanish to me", mean: "That seems strange to me", ex: "Sein Verhalten kommt mir spanisch vor.", exT: "His behaviour seems fishy to me." },
  { id: "de_kalte_schulter", rar: "epic", icon: "🧊", p: "Jemandem die kalte Schulter zeigen", lit: "To show someone the cold shoulder", mean: "To ignore someone on purpose", ex: "Seit dem Streit zeigt sie mir die kalte Schulter.", exT: "Since the argument she's been giving me the cold shoulder." },
  // legendary (batch 2)
  { id: "de_salat", rar: "legendary", icon: "🥗", p: "Da haben wir den Salat!", lit: "There we have the salad!", mean: "Now we're in a mess!", ex: "Ich hab's dir gesagt – jetzt haben wir den Salat!", exT: "I told you so — now look at the mess we're in!" },
  { id: "de_vogel", rar: "legendary", icon: "🐦", p: "Du hast einen Vogel!", lit: "You have a bird!", mean: "You're crazy!", ex: "Bei Schnee schwimmen gehen? Du hast doch einen Vogel!", exT: "Go swimming in the snow? You're nuts!" },
  { id: "de_leviten", rar: "legendary", icon: "📖", p: "Jemandem die Leviten lesen", lit: "To read someone the Levites", mean: "To give someone a stern talking-to", ex: "Der Chef hat ihm heute die Leviten gelesen.", exT: "The boss really read him the riot act today." },
  { id: "de_hase", rar: "legendary", icon: "🐰", p: "Mein Name ist Hase", lit: "My name is Hare", mean: "Don't ask me, I know nothing", ex: "Wer hat den Kuchen gegessen? – Mein Name ist Hase.", exT: "Who ate the cake? — Don't look at me." },
  { id: "de_puppen", rar: "epic", icon: "🪆", p: "Bis in die Puppen", lit: "Until the dolls", mean: "Until very late", ex: "Am Wochenende schlafe ich bis in die Puppen.", exT: "At the weekend I sleep until all hours." },
  { id: "de_loeffel", rar: "legendary", icon: "🥄", p: "Den Löffel abgeben", lit: "To hand in your spoon", mean: "To kick the bucket", ex: "Mein altes Handy hat endlich den Löffel abgegeben.", exT: "My old phone has finally given up the ghost." },
  { id: "de_tee", rar: "epic", icon: "🍵", p: "Abwarten und Tee trinken", lit: "Wait and drink tea", mean: "Be patient and see what happens", ex: "Die Ergebnisse kommen morgen – abwarten und Tee trinken.", exT: "The results come tomorrow — let's wait and see." },
  { id: "de_wald", rar: "legendary", icon: "🌲", p: "Ich glaub, ich steh im Wald!", lit: "I think I'm standing in the forest!", mean: "I can't believe what I'm seeing!", ex: "Die Miete steigt schon wieder? Ich glaub, ich steh im Wald!", exT: "The rent's going up again? You've got to be kidding me!" },
  // epic (batch 2)
  { id: "de_schlips", rar: "epic", icon: "👔", p: "Jemandem auf den Schlips treten", lit: "To step on someone's tie", mean: "To offend someone", ex: "Mit dem Witz bist du ihm auf den Schlips getreten.", exT: "You offended him with that joke." },
  { id: "de_korb", rar: "epic", icon: "🧺", p: "Jemandem einen Korb geben", lit: "To give someone a basket", mean: "To turn someone down", ex: "Sie hat ihm beim Tanzen einen Korb gegeben.", exT: "She turned him down for a dance." },
  { id: "de_wolke", rar: "epic", icon: "☁️", p: "Auf Wolke sieben schweben", lit: "To float on cloud seven", mean: "To be on cloud nine", ex: "Seit der Hochzeit schwebt sie auf Wolke sieben.", exT: "Since the wedding she's been on cloud nine." },
  { id: "de_auge", rar: "epic", icon: "😉", p: "Ein Auge zudrücken", lit: "To squeeze one eye shut", mean: "To turn a blind eye", ex: "Diesmal drücke ich noch ein Auge zu.", exT: "This time I'll let it slide." },
  { id: "de_gras", rar: "epic", icon: "🌱", p: "Ins Gras beißen", lit: "To bite into the grass", mean: "To bite the dust", ex: "Im Film beißt der Bösewicht am Ende ins Gras.", exT: "In the film the villain bites the dust at the end." },
  { id: "de_schmetterlinge", rar: "epic", icon: "🦋", p: "Schmetterlinge im Bauch haben", lit: "To have butterflies in your belly", mean: "To be in love", ex: "Wenn ich ihn sehe, habe ich Schmetterlinge im Bauch.", exT: "When I see him, I get butterflies." },
  { id: "de_hopfen", rar: "epic", icon: "🍻", p: "Da ist Hopfen und Malz verloren", lit: "Hops and malt are lost there", mean: "It's hopeless", ex: "Bei ihm ist Hopfen und Malz verloren.", exT: "He's a lost cause." },
  { id: "de_maus_faden", rar: "epic", icon: "🐭", p: "Da beißt die Maus keinen Faden ab", lit: "The mouse won't bite off a thread there", mean: "There's no way around it", ex: "Wir müssen um sechs los, da beißt die Maus keinen Faden ab.", exT: "We have to leave at six, no two ways about it." },
  { id: "de_kopf_waschen", rar: "epic", icon: "🧼", p: "Jemandem den Kopf waschen", lit: "To wash someone's head", mean: "To give someone a piece of your mind", ex: "Nach dem Unfall hat ihm sein Vater den Kopf gewaschen.", exT: "After the accident his father gave him a real earful." },
  { id: "de_perlen", rar: "epic", icon: "🦪", p: "Perlen vor die Säue werfen", lit: "To throw pearls before the sows", mean: "To waste something good on people who don't appreciate it", ex: "Ihm teuren Wein zu geben, heißt Perlen vor die Säue werfen.", exT: "Giving him expensive wine is a waste." },
  { id: "de_ohren_steif", rar: "epic", icon: "👂", p: "Die Ohren steif halten", lit: "To keep your ears stiff", mean: "To keep your chin up", ex: "Halt die Ohren steif, es wird besser!", exT: "Chin up, it'll get better!" },
  { id: "de_honig", rar: "epic", icon: "🍯", p: "Jemandem Honig ums Maul schmieren", lit: "To smear honey around someone's mouth", mean: "To butter someone up", ex: "Er schmiert dem Chef Honig ums Maul.", exT: "He's buttering up the boss." },
  { id: "de_porzellan", rar: "epic", icon: "🏺", p: "Wie ein Elefant im Porzellanladen", lit: "Like an elephant in a china shop", mean: "Clumsy and tactless", ex: "Er benimmt sich wie ein Elefant im Porzellanladen.", exT: "He's like a bull in a china shop." },
  { id: "de_krokodil", rar: "epic", icon: "🐊", p: "Krokodilstränen weinen", lit: "To cry crocodile tears", mean: "To fake being sad", ex: "Glaub ihr nicht, das sind nur Krokodilstränen.", exT: "Don't believe her, those are just crocodile tears." },
  { id: "de_ohren_viel", rar: "epic", icon: "📚", p: "Viel um die Ohren haben", lit: "To have a lot around your ears", mean: "To be very busy", ex: "Diese Woche habe ich viel um die Ohren.", exT: "I've got a lot on my plate this week." },
  { id: "de_eimer", rar: "epic", icon: "🪣", p: "Im Eimer sein", lit: "To be in the bucket", mean: "To be broken, ruined", ex: "Mein Laptop ist im Eimer.", exT: "My laptop is done for." },
  { id: "de_a_und_o", rar: "epic", icon: "🔤", p: "Das A und O", lit: "The A and the O", mean: "The most important thing", ex: "Beim Sprachenlernen ist Übung das A und O.", exT: "When learning languages, practice is everything." },
  { id: "de_nase_tanzen", rar: "epic", icon: "🕺", p: "Jemandem auf der Nase herumtanzen", lit: "To dance around on someone's nose", mean: "To walk all over someone", ex: "Die Kinder tanzen dem Babysitter auf der Nase herum.", exT: "The kids walk all over the babysitter." },
  { id: "de_eulen", rar: "epic", icon: "🦉", p: "Eulen nach Athen tragen", lit: "To carry owls to Athens", mean: "To do something pointless", ex: "Ihm Kaffee zu schenken, hieße Eulen nach Athen tragen – er hat ein Café.", exT: "Giving him coffee would be pointless — he owns a café." },
  { id: "de_spinne", rar: "epic", icon: "🕸️", p: "Ich glaub, ich spinne!", lit: "I think I'm spinning!", mean: "I can't believe this!", ex: "Du hast mein Auto genommen? Ich glaub, ich spinne!", exT: "You took my car? Unbelievable!" },
  { id: "de_hosen", rar: "epic", icon: "👖", p: "Die Hosen anhaben", lit: "To wear the trousers", mean: "To be the one in charge", ex: "Bei ihnen zu Hause hat sie die Hosen an.", exT: "She's the boss in their house." },
  { id: "de_falscher_fuss", rar: "epic", icon: "🥾", p: "Mit dem falschen Fuß aufstehen", lit: "To get up with the wrong foot", mean: "To get out of bed on the wrong side", ex: "Heute bin ich mit dem falschen Fuß aufgestanden.", exT: "I got out of bed on the wrong side today." },
  { id: "de_loecher", rar: "epic", icon: "🕳️", p: "Jemandem Löcher in den Bauch fragen", lit: "To ask holes into someone's belly", mean: "To pester someone with questions", ex: "Meine Nichte fragt mir Löcher in den Bauch.", exT: "My niece asks me endless questions." },
  { id: "de_butter_fische", rar: "epic", icon: "🐟", p: "Butter bei die Fische!", lit: "Butter with the fish!", mean: "Get to the point!", ex: "Jetzt mal Butter bei die Fische: Was willst du?", exT: "Come on, out with it: what do you want?" },
];

const IDIOMS_FR = [
  // legendary
  { id: "fr_lapin", rar: "legendary", icon: "🐇", p: "Poser un lapin", lit: "To put down a rabbit", mean: "To stand someone up", ex: "Je l'ai attendu une heure : il m'a posé un lapin !", exT: "I waited an hour for him: he stood me up!" },
  { id: "fr_poules_dents", rar: "legendary", icon: "🐔", p: "Quand les poules auront des dents", lit: "When hens have teeth", mean: "When pigs fly — never", ex: "Lui, ranger sa chambre ? Quand les poules auront des dents !", exT: "Him, tidy his room? When pigs fly!" },
  { id: "fr_carottes", rar: "legendary", icon: "🥕", p: "Les carottes sont cuites", lit: "The carrots are cooked", mean: "It's all over, nothing more can be done", ex: "On a raté le dernier train, les carottes sont cuites.", exT: "We missed the last train, it's game over." },
  { id: "fr_poil_main", rar: "legendary", icon: "✋", p: "Avoir un poil dans la main", lit: "To have a hair in your hand", mean: "To be very lazy", ex: "Il ne fait jamais rien, il a un poil dans la main.", exT: "He never does anything, he's bone idle." },
  { id: "fr_pommes", rar: "legendary", icon: "🍎", p: "Tomber dans les pommes", lit: "To fall into the apples", mean: "To faint", ex: "Il faisait si chaud qu'elle est tombée dans les pommes.", exT: "It was so hot that she fainted." },
  { id: "fr_langue_chat", rar: "legendary", icon: "😼", p: "Donner sa langue au chat", lit: "To give your tongue to the cat", mean: "To give up guessing", ex: "Je ne trouve pas la réponse, je donne ma langue au chat.", exT: "I can't find the answer, I give up." },
  { id: "fr_haricots", rar: "legendary", icon: "🫘", p: "C'est la fin des haricots", lit: "It's the end of the beans", mean: "It's the last straw, all is lost", ex: "Plus de café au bureau ? C'est la fin des haricots !", exT: "No more coffee at the office? It's the end of the world!" },
  { id: "fr_chat_gorge", rar: "epic", icon: "🐱", p: "Avoir un chat dans la gorge", lit: "To have a cat in your throat", mean: "To have a frog in your throat", ex: "Excusez-moi, j'ai un chat dans la gorge.", exT: "Sorry, I have a frog in my throat." },
  { id: "fr_doigts_nez", rar: "epic", icon: "👃", p: "Les doigts dans le nez", lit: "Fingers in the nose", mean: "Very easily, hands down", ex: "Il a gagné la course les doigts dans le nez.", exT: "He won the race hands down." },
  { id: "fr_moutons", rar: "legendary", icon: "🐑", p: "Revenons à nos moutons", lit: "Let's get back to our sheep", mean: "Let's get back to the subject", ex: "Bon, revenons à nos moutons : le budget.", exT: "Right, back to the point: the budget." },
  { id: "fr_anguille", rar: "legendary", icon: "🐍", p: "Il y a anguille sous roche", lit: "There's an eel under the rock", mean: "Something fishy is going on", ex: "Ils chuchotent depuis ce matin, il y a anguille sous roche.", exT: "They've been whispering all morning, something's up." },
  { id: "fr_trois_pommes", rar: "epic", icon: "🧒", p: "Haut comme trois pommes", lit: "As tall as three apples", mean: "Very small (of a child)", ex: "Je le connais depuis qu'il est haut comme trois pommes.", exT: "I've known him since he was knee-high." },
  // epic
  { id: "fr_cafard", rar: "epic", icon: "🪳", p: "Avoir le cafard", lit: "To have the cockroach", mean: "To feel down", ex: "Le dimanche soir, j'ai souvent le cafard.", exT: "On Sunday evenings I often feel blue." },
  { id: "fr_yeux_tete", rar: "epic", icon: "👀", p: "Coûter les yeux de la tête", lit: "To cost the eyes of your head", mean: "To cost an arm and a leg", ex: "Cette voiture coûte les yeux de la tête.", exT: "This car costs an arm and a leg." },
  { id: "fr_salades", rar: "epic", icon: "🥗", p: "Raconter des salades", lit: "To tell salads", mean: "To tell tall tales, to lie", ex: "Arrête de me raconter des salades !", exT: "Stop telling me stories!" },
  { id: "fr_peche", rar: "epic", icon: "🍑", p: "Avoir la pêche", lit: "To have the peach", mean: "To be full of energy", ex: "Ce matin, j'ai vraiment la pêche !", exT: "This morning I'm really full of beans!" },
  { id: "fr_grain_sel", rar: "epic", icon: "🧂", p: "Mettre son grain de sel", lit: "To put in your grain of salt", mean: "To butt in with your opinion", ex: "Il faut toujours qu'elle mette son grain de sel.", exT: "She always has to stick her oar in." },
  { id: "fr_cordes", rar: "epic", icon: "🌧️", p: "Il pleut des cordes", lit: "It's raining ropes", mean: "It's pouring", ex: "Prends un parapluie, il pleut des cordes.", exT: "Take an umbrella, it's pouring down." },
  { id: "fr_foudre", rar: "epic", icon: "⚡", p: "Avoir le coup de foudre", lit: "To get the lightning strike", mean: "To fall in love at first sight", ex: "Quand je l'ai vue, j'ai eu le coup de foudre.", exT: "When I saw her, it was love at first sight." },
  { id: "fr_lune", rar: "epic", icon: "🌙", p: "Être dans la lune", lit: "To be in the moon", mean: "To be daydreaming", ex: "Tu ne m'écoutes pas, tu es encore dans la lune.", exT: "You're not listening, you're daydreaming again." },
  { id: "fr_chats_fouetter", rar: "epic", icon: "🐈", p: "Avoir d'autres chats à fouetter", lit: "To have other cats to whip", mean: "To have other fish to fry", ex: "Désolé, j'ai d'autres chats à fouetter.", exT: "Sorry, I have more important things to do." },
  { id: "fr_grasse_matinee", rar: "epic", icon: "🛌", p: "Faire la grasse matinée", lit: "To do the fat morning", mean: "To sleep in", ex: "Le samedi, je fais la grasse matinée.", exT: "On Saturdays I have a lie-in." },
  { id: "fr_chat_chat", rar: "epic", icon: "🐾", p: "Appeler un chat un chat", lit: "To call a cat a cat", mean: "To call a spade a spade", ex: "Appelons un chat un chat : c'est un échec.", exT: "Let's call a spade a spade: it's a failure." },
  { id: "fr_pieds_plat", rar: "epic", icon: "🍽️", p: "Mettre les pieds dans le plat", lit: "To put your feet in the dish", mean: "To put your foot in it", ex: "En parlant de son divorce, j'ai mis les pieds dans le plat.", exT: "Mentioning his divorce, I really put my foot in it." },
  { id: "fr_casser_pieds", rar: "epic", icon: "🦶", p: "Casser les pieds à quelqu'un", lit: "To break someone's feet", mean: "To get on someone's nerves", ex: "Tu me casses les pieds avec tes questions !", exT: "You're driving me mad with your questions!" },
  { id: "fr_melon", rar: "epic", icon: "🍈", p: "Avoir le melon", lit: "To have the melon", mean: "To be big-headed", ex: "Depuis sa promotion, il a le melon.", exT: "Since his promotion he's got a big head." },
  { id: "fr_soupe_lait", rar: "epic", icon: "🥛", p: "Être soupe au lait", lit: "To be milk soup", mean: "To be quick-tempered", ex: "Attention, mon père est un peu soupe au lait.", exT: "Careful, my dad flares up easily." },
  { id: "fr_vers_nez", rar: "epic", icon: "🪱", p: "Tirer les vers du nez", lit: "To pull the worms out of someone's nose", mean: "To worm information out of someone", ex: "J'ai dû lui tirer les vers du nez pour savoir la vérité.", exT: "I had to drag the truth out of him." },
  { id: "fr_poire", rar: "epic", icon: "🍐", p: "Être une bonne poire", lit: "To be a good pear", mean: "To be a pushover", ex: "Il prête toujours son argent, c'est une bonne poire.", exT: "He always lends his money, he's a soft touch." },
  { id: "fr_mer_boire", rar: "epic", icon: "🌊", p: "Ce n'est pas la mer à boire", lit: "It's not the sea to drink", mean: "It's not that hard", ex: "Allez, deux pages à lire, ce n'est pas la mer à boire.", exT: "Come on, two pages to read, it's no big deal." },
  { id: "fr_faim_loup", rar: "epic", icon: "🐺", p: "Avoir une faim de loup", lit: "To have a wolf's hunger", mean: "To be starving", ex: "Après le sport, j'ai une faim de loup.", exT: "After sport I'm starving." },
  { id: "fr_pierre_coups", rar: "epic", icon: "🪨", p: "Faire d'une pierre deux coups", lit: "To make two hits with one stone", mean: "To kill two birds with one stone", ex: "Je passe à la poste en allant au travail : d'une pierre deux coups.", exT: "I'll stop at the post office on my way to work: two birds, one stone." },
  { id: "fr_rateau", rar: "epic", icon: "🧹", p: "Se prendre un râteau", lit: "To take a rake", mean: "To get turned down (romantically)", ex: "Il l'a invitée à danser et il s'est pris un râteau.", exT: "He asked her to dance and got turned down." },
  { id: "fr_dents_longues", rar: "epic", icon: "🦷", p: "Avoir les dents longues", lit: "To have long teeth", mean: "To be very ambitious", ex: "La nouvelle stagiaire a les dents longues.", exT: "The new intern is very ambitious." },
  { id: "fr_main_pate", rar: "epic", icon: "🥖", p: "Mettre la main à la pâte", lit: "To put your hand in the dough", mean: "To pitch in, to help", ex: "Tout le monde a mis la main à la pâte pour la fête.", exT: "Everyone pitched in for the party." },
  { id: "fr_mouche", rar: "epic", icon: "🪰", p: "Prendre la mouche", lit: "To take the fly", mean: "To take offence quickly", ex: "Ne prends pas la mouche, c'était une blague !", exT: "Don't get touchy, it was a joke!" },
  { id: "fr_fauche", rar: "epic", icon: "🌾", p: "Être fauché comme les blés", lit: "To be mown like the wheat", mean: "To be completely broke", ex: "À la fin du mois, je suis fauché comme les blés.", exT: "At the end of the month I'm flat broke." },
  { id: "fr_canard", rar: "epic", icon: "🦆", p: "Un froid de canard", lit: "A duck's cold", mean: "Freezing cold weather", ex: "Mets ton bonnet, il fait un froid de canard.", exT: "Put your hat on, it's freezing outside." },
  { id: "fr_pain_planche", rar: "epic", icon: "🍞", p: "Avoir du pain sur la planche", lit: "To have bread on the board", mean: "To have a lot of work to do", ex: "On a du pain sur la planche avant les vacances.", exT: "We've got our work cut out before the holidays." },
  { id: "fr_coq_ane", rar: "epic", icon: "🐓", p: "Passer du coq à l'âne", lit: "To go from the rooster to the donkey", mean: "To jump from one topic to another", ex: "Il passe toujours du coq à l'âne, je ne le suis plus.", exT: "He keeps jumping from topic to topic, I can't follow." },
  { id: "fr_assiette", rar: "epic", icon: "🍲", p: "Ne pas être dans son assiette", lit: "Not to be in your plate", mean: "To feel off, under the weather", ex: "Je ne suis pas dans mon assiette aujourd'hui.", exT: "I'm not feeling myself today." },
  { id: "fr_farine", rar: "epic", icon: "🎭", p: "Rouler quelqu'un dans la farine", lit: "To roll someone in flour", mean: "To con someone", ex: "Le vendeur nous a roulés dans la farine.", exT: "The salesman took us for a ride." },
  { id: "fr_chair_poule", rar: "epic", icon: "🐥", p: "Avoir la chair de poule", lit: "To have hen's flesh", mean: "To have goosebumps", ex: "Cette chanson me donne la chair de poule.", exT: "This song gives me goosebumps." },
  { id: "fr_petite_bete", rar: "epic", icon: "🐞", p: "Chercher la petite bête", lit: "To look for the little beast", mean: "To nitpick", ex: "Arrête de chercher la petite bête, c'est très bien.", exT: "Stop nitpicking, it's very good." },
  { id: "fr_coeur_main", rar: "epic", icon: "💗", p: "Avoir le cœur sur la main", lit: "To have your heart on your hand", mean: "To be very generous", ex: "Ma grand-mère a le cœur sur la main.", exT: "My grandmother is so generous." },
  { id: "fr_chocolat", rar: "epic", icon: "🍫", p: "Être chocolat", lit: "To be chocolate", mean: "To be left empty-handed, fooled", ex: "Plus de billets ! On est chocolat.", exT: "No tickets left! We've missed out." },
  { id: "fr_pain", rar: "epic", icon: "🥐", p: "Ça ne mange pas de pain", lit: "That doesn't eat bread", mean: "It costs nothing to try", ex: "Demande-lui, ça ne mange pas de pain.", exT: "Ask him, there's no harm in trying." },
  { id: "fr_charrue", rar: "epic", icon: "🐂", p: "Mettre la charrue avant les bœufs", lit: "To put the plough before the oxen", mean: "To put the cart before the horse", ex: "Acheter la robe avant la bague ? C'est mettre la charrue avant les bœufs.", exT: "Buying the dress before the ring? That's putting the cart before the horse." },
  // legendary (batch 2)
  { id: "fr_trente_et_un", rar: "legendary", icon: "🎩", p: "Être sur son trente-et-un", lit: "To be on your thirty-one", mean: "To be dressed to the nines", ex: "Pour le mariage, tout le monde était sur son trente-et-un.", exT: "Everyone was dressed to the nines for the wedding." },
  { id: "fr_trois_pattes", rar: "legendary", icon: "🦆", p: "Ça ne casse pas trois pattes à un canard", lit: "It doesn't break three legs off a duck", mean: "It's nothing special", ex: "Le film est sympa, mais ça ne casse pas trois pattes à un canard.", exT: "The film is fine, but nothing to write home about." },
  { id: "fr_araignee", rar: "legendary", icon: "🕷️", p: "Avoir une araignée au plafond", lit: "To have a spider on the ceiling", mean: "To be a bit crazy", ex: "Il parle à ses plantes ? Il a une araignée au plafond !", exT: "He talks to his plants? He's got a screw loose!" },
  { id: "fr_meme_orties", rar: "legendary", icon: "👵", p: "Il ne faut pas pousser mémé dans les orties", lit: "You mustn't push granny into the nettles", mean: "Don't push it too far", ex: "Une heure de retard, d'accord, mais trois… faut pas pousser mémé dans les orties !", exT: "An hour late, fine, but three… let's not push it!" },
  { id: "fr_fraises", rar: "legendary", icon: "🍓", p: "Sucrer les fraises", lit: "To sugar the strawberries", mean: "To get doddery with age", ex: "Mon grand-père commence à sucrer les fraises.", exT: "My grandfather is getting a bit doddery." },
  { id: "fr_epinards", rar: "epic", icon: "🥬", p: "Mettre du beurre dans les épinards", lit: "To put butter in the spinach", mean: "To earn a little extra money", ex: "Ce petit boulot met du beurre dans les épinards.", exT: "This side job brings in a bit of extra cash." },
  { id: "fr_haricot", rar: "legendary", icon: "🫛", p: "Courir sur le haricot", lit: "To run on the bean", mean: "To get on someone's nerves", ex: "Avec ta musique, tu me cours sur le haricot !", exT: "You're getting on my nerves with your music!" },
  { id: "fr_oignons", rar: "legendary", icon: "🧅", p: "Ce ne sont pas tes oignons", lit: "These aren't your onions", mean: "It's none of your business", ex: "Où je vais ce soir ? Ce ne sont pas tes oignons !", exT: "Where am I going tonight? Mind your own business!" },
  // epic (batch 2)
  { id: "fr_nues", rar: "epic", icon: "☁️", p: "Tomber des nues", lit: "To fall from the clouds", mean: "To be astonished", ex: "Quand il a appris la nouvelle, il est tombé des nues.", exT: "When he heard the news, he was flabbergasted." },
  { id: "fr_pluie_beau", rar: "epic", icon: "🌦️", p: "Faire la pluie et le beau temps", lit: "To make the rain and the fine weather", mean: "To call the shots", ex: "Dans cette entreprise, c'est lui qui fait la pluie et le beau temps.", exT: "In this company, he's the one who calls the shots." },
  { id: "fr_bras_long", rar: "epic", icon: "💪", p: "Avoir le bras long", lit: "To have a long arm", mean: "To have a lot of influence", ex: "Son oncle a le bras long, il lui a trouvé un stage.", exT: "His uncle has connections, he found him an internship." },
  { id: "fr_poisson_eau", rar: "epic", icon: "🐠", p: "Être comme un poisson dans l'eau", lit: "To be like a fish in water", mean: "To be in your element", ex: "Sur scène, elle est comme un poisson dans l'eau.", exT: "On stage, she's in her element." },
  { id: "fr_doigt_oeil", rar: "epic", icon: "👁️", p: "Se mettre le doigt dans l'œil", lit: "To put your finger in your eye", mean: "To be totally wrong", ex: "Si tu crois que je vais payer, tu te mets le doigt dans l'œil.", exT: "If you think I'm paying, you've got another think coming." },
  { id: "fr_coup_barre", rar: "epic", icon: "🥱", p: "Avoir un coup de barre", lit: "To get a blow from a bar", mean: "To suddenly feel exhausted", ex: "Après le déjeuner, j'ai toujours un coup de barre.", exT: "After lunch I always hit a wall." },
  { id: "fr_fouetter_chat", rar: "epic", icon: "😺", p: "Il n'y a pas de quoi fouetter un chat", lit: "There's nothing to whip a cat over", mean: "It's no big deal", ex: "Tu as cassé un verre ? Il n'y a pas de quoi fouetter un chat.", exT: "You broke a glass? It's no big deal." },
  { id: "fr_poire_deux", rar: "epic", icon: "🍐", p: "Couper la poire en deux", lit: "To cut the pear in two", mean: "To split the difference", ex: "Tu veux 100 €, j'en propose 60 : coupons la poire en deux.", exT: "You want €100, I offer 60: let's meet halfway." },
  { id: "fr_main_feu", rar: "epic", icon: "🔥", p: "En mettre sa main au feu", lit: "To put your hand in the fire for it", mean: "To swear by it", ex: "Il est honnête, j'en mettrais ma main au feu.", exT: "He's honest, I'd stake my life on it." },
  { id: "fr_trou", rar: "epic", icon: "🕳️", p: "Boire comme un trou", lit: "To drink like a hole", mean: "To drink like a fish", ex: "À la fête, il a bu comme un trou.", exT: "He drank like a fish at the party." },
  { id: "fr_yeux_ventre", rar: "epic", icon: "🍰", p: "Avoir les yeux plus gros que le ventre", lit: "To have eyes bigger than your belly", mean: "To take on more than you can handle", ex: "Trois desserts ? Tu as les yeux plus gros que le ventre !", exT: "Three desserts? Your eyes are bigger than your stomach!" },
  { id: "fr_chou_blanc", rar: "epic", icon: "🥬", p: "Faire chou blanc", lit: "To make white cabbage", mean: "To come away empty-handed", ex: "On a cherché des champignons, mais on a fait chou blanc.", exT: "We looked for mushrooms but came back empty-handed." },
  { id: "fr_anges", rar: "epic", icon: "😇", p: "Être aux anges", lit: "To be with the angels", mean: "To be over the moon", ex: "Depuis la naissance du bébé, ils sont aux anges.", exT: "Since the baby was born, they've been over the moon." },
  { id: "fr_pot", rar: "epic", icon: "🏺", p: "Tourner autour du pot", lit: "To go round the pot", mean: "To beat around the bush", ex: "Arrête de tourner autour du pot et dis-moi la vérité.", exT: "Stop beating around the bush and tell me the truth." },
  { id: "fr_eponge", rar: "epic", icon: "🧽", p: "Jeter l'éponge", lit: "To throw the sponge", mean: "To give up", ex: "Après trois échecs, il a jeté l'éponge.", exT: "After three failures, he threw in the towel." },
  { id: "fr_puce", rar: "epic", icon: "🦗", p: "Mettre la puce à l'oreille", lit: "To put the flea in someone's ear", mean: "To make someone suspicious", ex: "Son sourire m'a mis la puce à l'oreille.", exT: "His smile made me suspicious." },
  { id: "fr_poisson_rouge", rar: "epic", icon: "🐟", p: "Avoir une mémoire de poisson rouge", lit: "To have a goldfish's memory", mean: "To forget everything", ex: "J'ai encore oublié ton anniversaire, j'ai une mémoire de poisson rouge.", exT: "I forgot your birthday again, I have a memory like a sieve." },
  { id: "fr_langue_poche", rar: "epic", icon: "👅", p: "Ne pas avoir la langue dans sa poche", lit: "Not to have your tongue in your pocket", mean: "To be outspoken", ex: "Ma tante n'a pas la langue dans sa poche.", exT: "My aunt never minces her words." },
  { id: "fr_pied_gauche", rar: "epic", icon: "🦶", p: "Se lever du pied gauche", lit: "To get up on the left foot", mean: "To get out of bed on the wrong side", ex: "Il est grognon, il s'est levé du pied gauche.", exT: "He's grumpy, he got out of bed on the wrong side." },
  { id: "fr_pipe", rar: "epic", icon: "🪈", p: "Casser sa pipe", lit: "To break your pipe", mean: "To kick the bucket", ex: "Le vieux chat du voisin a cassé sa pipe.", exT: "The neighbour's old cat has kicked the bucket." },
  { id: "fr_fromage", rar: "epic", icon: "🧀", p: "En faire tout un fromage", lit: "To make a whole cheese of it", mean: "To make a big fuss about it", ex: "C'est juste une rayure, n'en fais pas tout un fromage !", exT: "It's just a scratch, don't make a song and dance about it!" },
  { id: "fr_artichaut", rar: "epic", icon: "💚", p: "Avoir un cœur d'artichaut", lit: "To have an artichoke heart", mean: "To fall in love easily", ex: "Elle tombe amoureuse chaque semaine, elle a un cœur d'artichaut.", exT: "She falls in love every week, she's so fickle-hearted." },
  { id: "fr_moutarde", rar: "epic", icon: "🌭", p: "La moutarde lui monte au nez", lit: "The mustard is rising to his nose", mean: "He's getting angry", ex: "Quand on l'interrompt, la moutarde lui monte au nez.", exT: "When people interrupt him, he starts to see red." },
  { id: "fr_ceinture", rar: "epic", icon: "🪢", p: "Se serrer la ceinture", lit: "To tighten your belt", mean: "To cut back on spending", ex: "Ce mois-ci, on doit se serrer la ceinture.", exT: "This month we have to tighten our belts." },
];

function idiomList() { return typeof IS_FRENCH_APP !== "undefined" && IS_FRENCH_APP ? IDIOMS_FR : IDIOMS_DE; }
function idiomOwned(id) { return !!(S.quests && S.quests.idioms && S.quests.idioms.includes(id)); }
// Unowned cards of a rarity (what a chest can still give).
function idiomPool(rar) { return idiomList().filter(c => c.rar === rar && !idiomOwned(c.id)); }
function idiomSectionHtml() {
  const list = idiomList();
  // Only the cards you own (legendary first); the rest is one line, not
  // a wall of locked tiles.
  const own = list.filter(c => idiomOwned(c.id)).sort((a, b) => (b.rar === "legendary") - (a.rar === "legendary"));
  const left = list.length - own.length, leftLeg = list.filter(c => c.rar === "legendary" && !idiomOwned(c.id)).length;
  return `<div class="stats-section-title" style="margin-top:14px">📜 Idioms · ${own.length}/${list.length}</div>
    ${own.length ? `<div class="idiom-grid">${own.map(c => `<button class="idiom-card r-${c.rar}" onclick="openIdiom('${c.id}')"><span class="idiom-icon">${c.icon}</span><span class="idiom-p">${escapeHtml(c.p)}</span><span class="idiom-mean">${escapeHtml(c.mean)}</span></button>`).join("")}</div>` : ""}
    ${left ? `<div class="idiom-left">🔒 ${left} still to find${leftLeg ? ` · ${leftLeg} legendary` : ""} — in Epic and Legendary chests</div>` : `<div class="idiom-left">✓ Every idiom collected!</div>`}`;
}
function openIdiom(id) {
  const c = idiomList().find(x => x.id === id);
  if (!c || !idiomOwned(id)) return;
  const old = document.getElementById("idiom-modal"); if (old) old.remove();
  const m = document.createElement("div");
  m.className = "modal-overlay"; m.id = "idiom-modal";
  m.onclick = e => { if (e.target === m) m.remove(); };
  m.innerHTML = `<div class="modal-sheet idiom-modal r-${c.rar}" role="dialog" aria-modal="true" aria-label="Idiom card">
    <div class="idiom-big-icon">${c.icon}</div>
    <div class="idiom-rar">${RARITY_INFO[c.rar].name} idiom</div>
    <div class="idiom-big-p">${escapeHtml(c.p)} ${typeof audioOk === "function" && audioOk() ? `<button class="audio-btn" ${speakBtnAttrs(c.p)}>🔊</button>` : ""}</div>
    <div class="idiom-row"><b>Word for word</b><span>${escapeHtml(c.lit)}</span></div>
    <div class="idiom-row"><b>Means</b><span>${escapeHtml(c.mean)}</span></div>
    <div class="idiom-ex">${escapeHtml(c.ex)} ${typeof audioOk === "function" && audioOk() ? `<button class="audio-btn" ${speakBtnAttrs(c.ex)}>🔊</button>` : ""}<small>${escapeHtml(c.exT)}</small></div>
    <div class="modal-actions"><button class="modal-btn primary" onclick="document.getElementById('idiom-modal').remove()">Close</button></div>
  </div>`;
  document.body.appendChild(m);
}
