// The ⚑ flag: appears after a recording, hides for the phone voice, note dialog, Settings copy/clear.
import fs from "node:fs";
import { launch, BASE, OUT } from "./common.mjs";
const S = OUT, B = BASE;
let pass = 0, fail = 0;
const ok = (c, msg, extra = "") => { if (c) { pass++; console.log("  ✓", msg); } else { fail++; console.log("  ✗ FAIL:", msg, extra); } };
const browser = await launch();
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: "block", deviceScaleFactor: 2 });
await ctx.grantPermissions(["clipboard-read", "clipboard-write"], { origin: B });
const page = await ctx.newPage(); const errs = []; page.on("pageerror", e => errs.push(e.message));
await page.addInitScript(() => {
  window.__toasts = []; window.__tts = []; speechSynthesis.speak = u => window.__tts.push(u.text);
  new MutationObserver(() => { const t = document.querySelector("#celebrate-toast .ct-title"); if (t && !window.__toasts.includes(t.textContent)) window.__toasts.push(t.textContent); }).observe(document, { childList: true, subtree: true });
});
await page.goto(`${B}/de/index.html`);
await page.waitForFunction(() => typeof AUDIO !== "undefined" && AUDIO.ready && AUDIO.remote, null, { timeout: 20000 });
await page.evaluate(() => { const o = document.getElementById("audio-offer"); if (o) o.remove(); });
await page.evaluate(() => audioDownload(["w", "s"]));
const on = () => page.evaluate(() => { const b = document.getElementById("audio-flag"); return !!b && b.classList.contains("on"); });
const playAndWait = t => page.evaluate(t => new Promise(res => { const el = _audioEl(); const h = () => { el.removeEventListener("playing", h); res(true); }; el.addEventListener("playing", h); speak(t); setTimeout(() => res(false), 3000); }), t);

console.log("1. the ⚑ appears only after a recording");
ok(!(await on()), "hidden before anything plays");
ok(await playAndWait("der Vater"), "a recording plays");
await page.waitForTimeout(150);
ok(await on(), "⚑ shows while/after it plays");
const box = await page.evaluate(() => { const r = document.getElementById("audio-flag").getBoundingClientRect(); return { x: r.x, w: r.width, h: r.height, right: innerWidth - r.right }; });
ok(box.w <= 30 && box.h <= 42 && Math.abs(box.right) < 1, `small and on the right edge (${Math.round(box.w)}×${Math.round(box.h)} px)`);
await page.screenshot({ path: `${S}/flag-button.png` });
await page.evaluate(() => speak("Ein Satz, den es im Paket nicht gibt, zum Testen."));
await page.waitForTimeout(100);
ok(!(await on()), "hides at once when the next thing uses the phone voice");
ok(await playAndWait("die Straße"), "another recording plays");
await page.waitForTimeout(150);
ok(await on() && await page.evaluate(() => document.getElementById("audio-flag").dataset.text) === "die Straße", "⚑ points at the phrase just heard");
await page.waitForFunction(() => _audioEl().ended, null, { timeout: 10000 });
await page.waitForTimeout(5600);
ok(!(await on()), "fades away ~5 s after the recording ends");

console.log("2. flagging with a note");
await playAndWait("je … desto"); await page.waitForTimeout(150);
await page.click("#audio-flag");
ok(await page.isVisible("#audio-flag-sheet"), "tap opens the small dialog");
ok((await page.textContent("#audio-flag-sheet .af-phrase")).includes("je … desto"), "it shows the phrase");
await page.screenshot({ path: `${S}/flag-sheet.png` });
await page.click("#af-play"); await page.waitForTimeout(200);
ok(!(await on()), "▶ replays without the ⚑ popping up over the dialog");
await page.fill("#af-note", "still a bit French");
await page.click("#af-yes");
ok(!(await page.isVisible("#audio-flag-sheet")), "dialog closes");
ok((await page.evaluate(() => window.__toasts)).includes("Flagged"), "'Flagged' toast");
ok(await page.evaluate(() => audioFlagCount()) === 1, "1 flag stored");
await playAndWait("der Vater"); await page.waitForTimeout(150); await page.click("#audio-flag");
await page.click("#af-yes");                                         // no note: optional
await playAndWait("je … desto"); await page.waitForTimeout(150); await page.click("#audio-flag");
ok(await page.inputValue("#af-note") === "still a bit French" && (await page.textContent("#af-yes")) === "Update", "flagging again shows the old note (Update)");
await page.fill("#af-note", "French je | and cut");
await page.keyboard.press("Enter");
ok(await page.evaluate(() => audioFlagCount()) === 2, "Enter saves; same phrase is updated, not duplicated (2 flags)");
await playAndWait("die Straße"); await page.waitForTimeout(150); await page.click("#audio-flag");
await page.keyboard.press("Escape");
ok(!(await page.isVisible("#audio-flag-sheet")) && await page.evaluate(() => audioFlagCount()) === 2, "Escape cancels, nothing stored");
await page.reload(); await page.waitForFunction(() => typeof AUDIO !== "undefined" && AUDIO.ready);
ok(await page.evaluate(() => audioFlagCount()) === 2, "flags survive a restart");

console.log("3. Settings → Sound & voice");
await page.evaluate(() => { const o = document.getElementById("audio-offer"); if (o) o.remove(); openSettings("sound"); });
await page.waitForTimeout(400);
const rows = await page.$$eval(".settings-item .set-label", els => els.map(e => e.textContent));
const logRows = rows.filter(t => /voice log|flagged|without a recording/i.test(t));
ok(logRows.length === 1 && logRows[0] === "Copy voice log · 3", "one row: Copy voice log · 3 (2 flagged + 1 without a recording)", JSON.stringify(logRows));
await page.screenshot({ path: `${S}/flag-settings.png`, fullPage: false });
await page.click("text=Copy voice log · 3"); await page.waitForTimeout(300);
const clip = await page.evaluate(() => navigator.clipboard.readText());
console.log("   copied:\n" + clip.split("\n").map(l => "     " + l).join("\n"));
ok(/^Voice log \(German, pack [0-9a-f]+\):\nFlagged recordings:\nje … desto \| French je \/ and cut\nder Vater\nPhrases without a recording:\nEin Satz, den es im Paket nicht gibt, zum Testen\.$/.test(clip), "both lists in one copy");
ok(await page.evaluate(() => audioFlagCount() + audioMissCount()) === 0, "copying empties the log");
ok(!(await page.$$eval(".settings-item .set-label", els => els.map(e => e.textContent))).some(t => /voice log/i.test(t)), "the row disappears when the log is empty");
ok(errs.length === 0, "no page errors", errs.join(" | "));
fs.writeFileSync(`${S}/flag-clip.txt`, clip);
await browser.close();
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
